### PR TITLE
Fix: Add support for nativeTokens/feature in sendAdvanced

### LINKED ISSUE #1025: Native tokens are serialized as empty array and burnt after calling buildTransactionPayload
## Bug description

Native tokens are serialized as empty array in sendAdvanced.ts/buildTransactionPayload

## Version

feat/stardust

- Version:

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL: https://api.shimmer.network
- Network: Shimmer

## Hardware specification

What hardware are you using?
MAC

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. prepare a block w/ outputs having native tokens
2. call buildTransactionPayload in sendAdvanced.ts
3. natives tokens are serialized as empty array and burnt unexpectedly

## Expected behaviour

native tokens not getting lost

## Actual behaviour

no native tokens in target outputs

## Errors

n/a

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

- Added support for optionally defining nativeTokens and features for outputs in highLevel/sendAdvanced.ts

Fixes https://github.com/iotaledger/iota.js/issues/1025

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by abbasabid — CHANGES_REQUESTED** [review]
Is there any reason why these empty validation files have been added?

File: packages/iota/src/highLevel/sendAdvanced.ts [hunk 1]
```diff
@@ -48,6 +50,8 @@ export async function sendAdvanced(
         address: string;
         addressType: number;
         amount: BigInteger;
+        nativeTokens?: INativeToken[];
+        fatures?: FeatureTypes[];
```
Comment (brancoder) [inline packages/iota/src/highLevel/sendAdvanced.ts]: We should also add the unlock conditions.

File: packages/iota/src/highLevel/sendAdvanced.ts [hunk 2]
```diff
@@ -149,7 +159,7 @@ export function buildTransactionPayload(
             const o: IBasicOutput = {
                 type: BASIC_OUTPUT_TYPE,
                 amount: output.amount.toString(),
-                nativeTokens: [],
+                nativeTokens: output.nativeTokens,
                 unlockConditions: [
```
Comment (brancoder) [inline packages/iota/src/highLevel/sendAdvanced.ts:163]: Looks like the unlock conditions are hardcoded here. This will cause any additional unlock conditions, other than Address unlock condition, to be discarded.  
Also outputs other than Basic are not taken in to consideration.
Looks like the whole sendAdvanced function needs a refactor :)

**Review by brancoder — CHANGES_REQUESTED** [review]
Remove two added empty validation files.

File: packages/iota/src/highLevel/sendAdvanced.ts (hunk 1 above)
Comment (brancoder) [inline packages/iota/src/highLevel/sendAdvanced.ts]: Fix the typo in word `fatures`.

**Review by brancoder — APPROVED** [review]

**Review by abbasabid — APPROVED** [review]
