### PR TITLE
Fix: Add balance from expired outputs in total balance

### LINKED ISSUE #955: [Task]: Add balance from expired outputs
## Description

Update  high level addressBalance function to take in considaration If an output is expired (time in the expiration unlock condition passed without it getting consumed before), then the amount of the output should be added to the balance of the return address

Related to explorer issue: https://github.com/iotaledger/explorer/issues/353

### PR DESCRIPTION
**Pull request by abbasabid**
# Description of change

- Updated `addressBalance` function to also add expired outputs amount to the balance of the return address.

fixes https://github.com/iotaledger/iota.js/issues/955

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/iota/src/highLevel/addressBalance.ts [hunk 1]
```diff
@@ -53,6 +54,21 @@ export async function addressBalance(
         cursor = response.cursor;
     } while (cursor && response.items.length > 0);
 
+    do {
+        expirationResponse = await indexerPluginClient.outputs({
+            expirationReturnAddressBech32: addressBech32, expiresBefore: Math.floor(Date.now() / 1000), cursor
```
Comment (msarcev) [inline packages/iota/src/highLevel/addressBalance.ts]: Reusing the same `cursor` without "resetting" ? This could result in first request having a `cursor` from `do` block above which is unrelated.

File: packages/iota/src/highLevel/addressBalance.ts [hunk 2]
```diff
@@ -53,6 +54,21 @@ export async function addressBalance(
...
+        });
+
+        for (const outputId of expirationResponse.items) {
+            const output = await localClient.output(outputId);
+
+            if (!output.metadata.isSpent) {
+                total = total.plus(output.output.amount);
+            }
+        }
+        cursor = response.cursor;
```
Comment (brancoder) [inline packages/iota/src/highLevel/addressBalance.ts]: Change to expirationResponse.cursor

File: packages/iota/src/highLevel/addressBalance.ts (hunk 1 above)
Comment (abbasabid) [reply packages/iota/src/highLevel/addressBalance.ts]: Resolved.

File: packages/iota/src/highLevel/addressBalance.ts (hunk 2 above)
Comment (abbasabid) [reply packages/iota/src/highLevel/addressBalance.ts]: Resolved.

**Review by brancoder — APPROVED** [review]
