### PR TITLE
Retry with larger depth if reference transaction is too old

### LINKED ISSUE #264: Retry with larger depth if reference transaction is too old
### Bug description
If `getTransactionsToApprove()` is called with an old reference in relation to a given depth, the call will sometimes fail with [`"Reference transaction is too old"`](https://github.com/iotaledger/iri/blob/06ad631a438b07e932ea3de58ffac6e4c5b6e74b/src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java#L123) exception. This has an impact on promotion with `promoteTransaction()` which doesn't recover after failure, assuming reference is still consistent.

### Steps To Reproduce
1. Call `getTransactionsToApprove()` with small depth on a relatively old reference
2. Promote a relatively old reference with small depth by calling `promoteTransaction()`

### Expected behaviour
`promoteTransaction()` should be able to recover as long as reference transaction is consistent & above max depth. It should recall `getTransactionsToApprove()` with larger depth (`<= maxDepth`).

### Actual behaviour
`getTransactionsToApprove()` fails with exception & `promoteTransaction()` stops working for relatively small depth.

### Requirements
- [ ] `promoteTransaction()` recovers from `"Reference transaction is too old"` exception, on _consistent_ txs, by increasing the depth up to `maxDepth = 15`

### Open Questions
- [ ] Should we enable retries by default in `getTransactionsToApprove()`?

### Am I planning to do it myself with a PR?
Yes

### PR DESCRIPTION
**Pull request by chrisdukakis**
# Description

If `getTransactionsToApprove()` is called with an old reference in relation to a given depth, the call will sometimes fail with [`"Reference transaction is too old"`](https://github.com/iotaledger/iri/blob/06ad631a438b07e932ea3de58ffac6e4c5b6e74b/src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java#L123) exception.

This PR addresses this issue by adding `adjustDepth` option to `getTransactionsToApprove`. This feature is now utilized by default in `promoteTransaction()`. If the option is set to true, `depth` is incremented upon failure, up to `maxDepth` (which is currently `15`).

Fixes #264 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Promoting transaction and observing `depth` in `getTransactionsToApprove` requests.
- [x] Manually tested `sendTransfer`/`sendTrytes`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: lib/api/api.js [hunk 1]
```diff
@@ -316,7 +332,17 @@ api.prototype.getTransactionsToApprove = function(depth, reference, callback) {
 
     var command = apiCommands.getTransactionsToApprove(depth, reference);
 
-    return this.sendCommand(command, callback)
+    return this.sendCommand(command, function (err, tips) {
+      if (adjustDepth && err && err.message.indexOf(REFERENCE_TRANSACTION_TOO_OLD) > -1 && ++depth <= maxDepth) {
```
Comment (laumair) [inline lib/api/api.js]: Can we retry with doubling the depth? This would reduce the network calls. However, will increase the load on node.

Comment (chrisdukakis) [reply lib/api/api.js]: That's an interesting idea. However I think that requests won't be many, most likely just one extra request, if promotion is non-stop and tx is consistent/attached above max depth. We can optimize more by adjusting the depth with a time heuristic...
